# Generated by Django 5.2.8 on 2025-11-06 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente_id', models.CharField(max_length=20, unique=True, verbose_name='ID del Expediente')),
                ('tipo', models.CharField(choices=[('solicitud', 'Solicitud'), ('oficio', 'Oficio'), ('informe', 'Informe'), ('constancia', 'Constancia')], max_length=20, verbose_name='Tipo de Documento')),
                ('remitente', models.CharField(max_length=200, verbose_name='Remitente')),
                ('asunto', models.TextField(verbose_name='Asunto')),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('en_revision', 'En revisión'), ('derivado', 'Derivado'), ('en_proceso', 'En proceso'), ('atendido', 'Atendido'), ('archivado', 'Archivado')], default='recibido', max_length=20, verbose_name='Estado')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Archivo Adjunto')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_organizativa', models.CharField(blank=True, max_length=100)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Movimiento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('tipo', models.CharField(choices=[('creacion', 'Creación de Expediente'), ('derivacion', 'Derivación'), ('atencion', 'Atención'), ('archivo', 'Archivado')], max_length=20)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.documento')),
                ('unidad_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_recibidos', to='gestion.perfilusuario')),
                ('usuario_origen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_enviados', to='gestion.perfilusuario')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='responsable_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_a_cargo', to='gestion.perfilusuario'),
        ),
    ]
